[package]
name = "engine"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
uuid = { version = "0.8.1", features = ["v4"] }
anyhow = "1.0.37"
libc = "0.2.81"
