[package]
name = "engine"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.0.2", features = ["full"] }
uuid = { version = "0.8.2", features = ["v4"] }
anyhow = "1.0.38"
