[package]
name = "protocol"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
tonic = "0.3.1"
prost = "0.6"

[build-dependencies]
tonic-build = "0.3.1"
