[package]
name = "protocol"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
tonic = "0.4.0"
prost = "0.7.0"

[build-dependencies]
tonic-build = "0.4.0"
