name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        rustup install stable-2020-11-19-x86_64-unknown-linux-gnu
        rustup component add rustfmt --toolchain stable-2020-11-19-x86_64-unknown-linux-gnu
        rustup component add clippy --toolchain stable-2020-11-19-x86_64-unknown-linux-gnu
    - name: style
      run: cargo fmt -- --check
    - name: clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        rustup install stable-2020-11-19-x86_64-unknown-linux-gnu
        rustup component add rustfmt --toolchain stable-2020-11-19-x86_64-unknown-linux-gnu
        rustup component add clippy --toolchain stable-2020-11-19-x86_64-unknown-linux-gnu
    - name: test
      run: cargo test
